spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop  # ✅ 데이터베이스 테이블 자동 생성 설정 (필요에 따라 create / update 선택)

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb  # ✅ 잘못된 설정을 제거하고 원래대로 유지
    driver-class-name: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8  # ✅ SQL 파일을 UTF-8로 읽도록 설정

  h2:
    console:
      enabled: true
      path: /h2-console  # ✅ H2 콘솔 접속을 위한 경로 설정

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot